version: '2.4'

services:
  jupyter:
    build: ./jupyter
    volumes:
      - ./notebooks:/notebooks
    ports:
      - "8888:8888"
    networks:
      - tf
    runtime: nvidia

networks:
  tf:
    driver: bridge
